Feature/ct 2
slver-dragon/Starter pull request #2
Opened 2021-04-15 12:59 UTC by slver-dragon

Надеюсь последний

2021-04-15 17:18 UTC, DenisKalyanov requested changes

2021-04-15 17:18 UTC, DenisKalyanov commented on css/style.css
> +    top: 0;
Зачем тут top, left, если они работают только со свойством  "position: ....."

2021-04-15 17:18 UTC, DenisKalyanov commented on css/style.css
> +    /*width: 68%;*/
комментарии из кода удаляем.

2021-04-15 17:18 UTC, DenisKalyanov commented on css/style.css
> +    height: 2%;
Что за высота такая интересная 2%, для чего она?
Ведь этот блок всегда будет в desctop версии определённой высоты.

2021-04-15 17:18 UTC, DenisKalyanov commented on css/style.css
> +    flex-direction: row;
flex-direction: row; по дефолту у display: flex;
Поэтому его указывать не обязательно.

2021-04-15 17:18 UTC, DenisKalyanov commented on css/style.css
> +    color: black;
Цвета мы обозначаем:
#FFFFFF
rgb(xx, xx, xx);
rgba(xx, xx, xx, 0.x);

2021-04-15 17:18 UTC, DenisKalyanov commented on css/style.css
> +        display: inline-block;
Почему ты решил тут использовать именно` inline-block;`

2021-04-15 17:18 UTC, DenisKalyanov commented on css/style.css
> +        background: #ff352b;
background-color: #ff352b;

2021-04-15 17:18 UTC, DenisKalyanov commented on css/style.css
> +        flex-direction: row;
flex-direction: row; - по умолчанию оно row

2021-04-15 17:18 UTC, DenisKalyanov commented on css/style.css
> +        width: 110%;
Почему у него ширина больше блока в котором он лежит?

2021-04-15 17:18 UTC, DenisKalyanov commented on css/style.css
> +        height: 10%;
И высоту мы не фиксируем, тем более в процентах.
Высота у нас вообще не должна изменяться в header. У нас высота изменяется в том случае, если блок сжимается, в нём много текста, и текст переноситься на другую строку и высота блока должна увеличиваться.

2021-04-15 17:18 UTC, DenisKalyanov commented on css/style.css
> +        width: 381px;
так, ну у нас размеры то в %, то в px, то в rem...
Осталось ещё приплести сюда em, vw, vh... :)
Это я к тому, что если пишем в rem, то px уже не используем.

2021-04-15 17:18 UTC, DenisKalyanov commented on css/style.css
> +        display: flex;
display: flex;

2021-04-15 17:18 UTC, DenisKalyanov commented on css/style.css
> +        display: block;
display: block;
 
 Так в итоге какой display>?
 Свойство display может быть только 1, в данном случае код читается сверху вниз, поэтому первый display не сработает.

2021-04-15 17:18 UTC, DenisKalyanov commented on css/style.css
> +        top: 23%;
Ну вот почему высота в процентах?
Он же всегда будет на одном и том же расстоянии от верха, поэтому высоту можно фиксировать.
А % используются, когда высота  должна зависит от каких-то факторов.

2021-04-15 17:18 UTC, DenisKalyanov commented on css/style.css
> +        left: 10%;
Если эта картинка должна быть по центру,  то посмотри как выставляется блок по центру при position: absolute;

2021-04-15 17:18 UTC, DenisKalyanov commented on index.html
> +          <div class="wrapper-mid-left">
wrapper-mid-left так mid или left? 
И если уже есть класс с именем left, то по логике должен быть класс с именем и right, но...

2021-04-15 18:06 UTC, slver-dragon commented on css/style.css
> +    height: 2%;
Данная высота в % чтобы не делать лишних высот в мобильной версии. Без этих 2% в мобильной нужно будет отдельно прописывать высоту.

2021-04-15 18:55 UTC, slver-dragon commented on index.html
> +          <div class="wrapper-mid-left">
mid это по вертикали (top,mid), left - горизонталь, при наличии был бы center

2021-04-16 08:09 UTC, slver-dragon commented on css/style.css
> +    top: 0;
исправил

2021-04-16 08:09 UTC, slver-dragon commented on css/style.css
> +    /*width: 68%;*/
исправил

2021-04-16 08:09 UTC, slver-dragon commented on css/style.css
> +    flex-direction: row;
удалил

2021-04-16 08:10 UTC, slver-dragon commented on css/style.css
> +    color: black;
заменил

2021-04-16 08:13 UTC, slver-dragon commented on css/style.css
> +        left: 10%;
Поправил

2021-04-16 08:14 UTC, slver-dragon commented on css/style.css
> +        top: 23%;
Поправил

2021-04-16 08:19 UTC, slver-dragon commented on css/style.css
> +        display: block;
определился

2021-04-16 08:22 UTC, slver-dragon commented on css/style.css
> +        width: 381px;
забыл перевести, поправил

2021-04-16 08:24 UTC, slver-dragon commented on css/style.css
> +        height: 10%;
поправил

2021-04-16 08:29 UTC, slver-dragon commented on css/style.css
> +        width: 110%;
Удалил ширину, расширив родительский блок

2021-04-16 08:30 UTC, slver-dragon commented on css/style.css
> +        flex-direction: row;
Убрал

2021-04-16 08:31 UTC, slver-dragon commented on css/style.css
> +        background: #ff352b;
Поправил

2021-04-16 08:33 UTC, slver-dragon commented on css/style.css
> +        display: inline-block;
Если честно, не помню, убрал.

2021-04-19 07:32 UTC, slver-dragon commented on css/style.css
> +    top: 0;
+

2021-04-19 07:33 UTC, slver-dragon commented on css/style.css
> +    /*width: 68%;*/
+

2021-04-19 07:33 UTC, slver-dragon commented on css/style.css
> +    height: 2%;
+

2021-04-19 07:34 UTC, slver-dragon commented on css/style.css
> +    flex-direction: row;
+

2021-04-19 07:35 UTC, slver-dragon commented on css/style.css
> +    color: black;
+

2021-04-19 07:37 UTC, slver-dragon commented on css/style.css
> +        display: inline-block;
+

2021-04-19 07:39 UTC, slver-dragon commented on css/style.css
> +        background: #ff352b;
+

2021-04-19 07:39 UTC, slver-dragon commented on css/style.css
> +        flex-direction: row;
+

2021-04-19 07:40 UTC, slver-dragon commented on css/style.css
> +        width: 110%;
+

2021-04-19 07:41 UTC, slver-dragon commented on css/style.css
> +        height: 10%;
+

2021-04-19 07:41 UTC, slver-dragon commented on css/style.css
> +        width: 381px;
+

2021-04-19 07:42 UTC, slver-dragon commented on css/style.css
> +        display: block;
+

2021-04-19 07:44 UTC, slver-dragon commented on css/style.css
> +        left: 10%;
+

2021-04-19 07:44 UTC, slver-dragon commented on index.html
> +          <div class="wrapper-mid-left">
Перепланирована маркировка

2021-04-19 09:05 UTC, DenisKalyanov requested changes

2021-04-19 09:05 UTC, DenisKalyanov commented on index.html
> +        <!--<div class="wrapper-mid">-->
Это зачем?

2021-04-19 09:05 UTC, DenisKalyanov commented on css/style.css
> +        top: 11%; left: 0%; bottom: 0%; right: 0%;
top: 11%; left: 0%; bottom: 0%; right: 0%; 
Это как?) У тебя есть элемент, ты ему говоришь, будь на 11% от верха. Далее ты говоришь ему будь впритык к левому краю left: 0%;, потом ты ему говоришь. будь ещё впритык к нижнему края bottom: 0%; и ещё будь впритык к правому краю right: 0%;

Мы указываем 
top: "РАССТОЯНИЕ ОТ ВЕРХНЕГО КРАЯ"
left: "РАССТОЯНИЕ ОТ ЛЕВОГО КРАЯ"
и т.д.

Что б выровнять абсолютный элемент по центру родителя:
top:50%;
left:50%;
transform:translate(-50%, -50%);

2021-04-19 09:11 UTC, slver-dragon commented on index.html
> +        <!--<div class="wrapper-mid">-->
Снова забыл удалить закомментированый фрагмент.

2021-04-19 09:58 UTC, slver-dragon commented on css/style.css
> +        top: 11%; left: 0%; bottom: 0%; right: 0%;
Поправил

2021-04-19 11:37 UTC, merged