feature/CT-3: -first probe
slver-dragon/Starter pull request #3
Opened 2021-04-22 15:31 UTC by slver-dragon

Первая опытка.

2021-04-23 08:07 UTC, DenisKalyanov requested changes

2021-04-23 08:07 UTC, DenisKalyanov commented on css/style.css
> +        margin-right: auto;
```
margin-left: auto;
margin-right: auto; 
```
Это тоже самое что написать 
`margin: auto;`

> margin: auto;               /* верх и низ: отступ 0 */
>                             /* блок отцентрирован горизонтально */

2021-04-23 08:07 UTC, DenisKalyanov commented on css/style.css
> +        width: 81.5625rem;
Ты зафиксировал ширину, при изменении разрешения, она будет всё время одинаковая и всё сломается.

2021-04-23 08:07 UTC, DenisKalyanov commented on index.html
> +              <p>Переезд за 4 часа</p>
```
 <p>1 фургон</p>
 <p>2 грузчика</p>
 <p>Переезд за 4 часа</p>
```

Можно ли всё это объеденить в тег `<pre>` ?

2021-04-23 08:07 UTC, DenisKalyanov commented on index.html
> +            <div class="trans" >
`trans` - это какие-то мужчины из тайланда? :)
У нас тут что, описание? `description`

2021-04-23 08:07 UTC, DenisKalyanov commented on index.html
> +            <h1>100 руб.</h1>
Воу воу. Парочку правил про headers h1, h2, h3...
1) Для начала, заголовок на странице h1 может быть только 1!
2) Мы можем сказать, что это  title? НЕТ, это просто цена, можно заключить в `span` стилизовать.
Мы используем headers в заголовках блока, ну тут это явно не заголовок.

2021-04-23 08:07 UTC, DenisKalyanov commented on index.html
> +        <h1>Автопарк</h1>
h1 только 1 на странице.

2021-04-23 08:07 UTC, DenisKalyanov commented on index.html
> +          <li><a href="#">Газели</a></li>
Я писал в теории когда лучше использовать тег `a`.
А когда лучше использовать тег `button`.

2021-04-23 08:07 UTC, DenisKalyanov commented on index.html
> +          <a href="#" class="main-third-back">&lt;</a>
`&lt; `что это?
И почему это тег `a`?

2021-04-23 08:07 UTC, DenisKalyanov commented on index.html
> +            <span class="main-third-Hmenu-element"></span>
`main-third-Hmenu-element`
1. Мы не используем заглавные буквы в названии классов.
2. Ну уж очень огромное название класса для обычной точки. Если бы внутри был ещё один span, то ты бы называл класс:
`main-third-Hmenu-element-something`, а потом ещё что-то 
`main-third-Hmenu-element-something-something-something`
Закапываешься.

2021-04-23 08:07 UTC, DenisKalyanov commented on index.html
> +              <h2>Ирина</h2>
Ну зачем `Ирине` быть заголовком?

2021-04-23 08:07 UTC, DenisKalyanov commented on index.html
> +              <a class="read-after" href="#">Читать полностью</a>
Почему это `<a>`?

2021-04-23 08:07 UTC, DenisKalyanov commented on index.html
> +              <nobr>
Зачем этот тег? Страница же будет ломаться.

2021-04-23 08:07 UTC, DenisKalyanov commented on index.html
> +              <h2>Ольга Петрова</h2>
это не заголовок

2021-04-23 08:07 UTC, DenisKalyanov commented on index.html
> +              <a class="read-after" href="#">Читать полностью</a>
Это не должно быть тегом `<a>`

2021-04-23 08:07 UTC, DenisKalyanov commented on css/style.css
> +        padding: .495rem 4.8125rem;
.495rem?
0.495rem будет правильно.

2021-04-23 08:07 UTC, DenisKalyanov commented on css/style.css
> +        margin: .625rem 0rem 1.1875rem;
0.625rem

2021-04-23 08:07 UTC, DenisKalyanov commented on css/style.css
> +
```
.pict-man-mob {
        display: flex;
        position: absolute;
        margin: auto;
        top:55%; left:50%;
        transform:translate(-50%, -50%);
    }
```

А зачем тут и 
```
display: flex;
position: absolute;
margin: auto;
```
В ДАННОМ СЛУЧАЕ
display: flex;  -не работает
margin: auto;-не работает

2021-04-23 08:07 UTC, DenisKalyanov commented on css/style.css
> +        position: absolute;
ИЛИ `display: flex;  `   ИЛИ   `position: absolute;`

2021-04-23 08:07 UTC, DenisKalyanov commented on css/style.css
> +        width: 69.125rem;
Что случиться когда ширина окна составит 60rem?  Это около 1000px

2021-04-23 08:07 UTC, DenisKalyanov commented on css/style.css
> +        margin: 0% 0% 5%;
0 === 0% === 0rem === 0px

2021-04-23 08:07 UTC, DenisKalyanov commented on css/style.css
> +        margin-right: auto;
margin-left: auto;
margin-right: auto;

Чтобы правильно применять эти команды, нужно понимать что они делают.

2021-04-23 08:07 UTC, DenisKalyanov commented on css/style.css
> +        width: 120rem;
А если страница будет меньше 120rem? Что произойдёт тогда

2021-04-23 08:07 UTC, DenisKalyanov commented on css/style.css
> +        width: 26.3125rem;
**` width: 26.3125rem`;** ЧТО мы тут имеем, для начала это **416px**
А ты прописываешь в этом блока стили, для разрешения **`320px`** Я немного не улавливаю логики.

2021-04-23 08:07 UTC, DenisKalyanov commented on css/style.css
> +        height: .125rem;
0.125rem; Нужно использовать с нулём. 
Кто-то говорит, что круто писать без нуля, но эти люди наверно не писали на SASS u VUE, там ты можешь получить ошибку, возможно в REACT будет похожая схема, или prettier на других проектах будет ругаться и считать это ошибкой и придётся переучиваться обратно.

2021-04-23 08:07 UTC, DenisKalyanov commented on css/style.css
> +        width: 26.25rem;
Ну как так? Если ширина всего блока не может быть больше 20rem

2021-04-23 08:07 UTC, DenisKalyanov commented on index.html
> +        <h1>Как это происходит?</h1>
`<h1>` только один на странице может быть.

2021-04-23 08:07 UTC, DenisKalyanov commented on index.html
> +            <div class="main-first-number">01</div>
ради цифры 01 целый `div`, лучше  `span`

2021-04-23 08:07 UTC, DenisKalyanov commented on index.html
> +          <div class="main-first-element">
main-first-element

2021-04-23 08:07 UTC, DenisKalyanov commented on index.html
> +          <div class="main-first-element">
main-first-element

2021-04-23 08:07 UTC, DenisKalyanov commented on index.html
> +            <div class="main-first-number">02</div>
main-first-number

2021-04-23 08:07 UTC, DenisKalyanov commented on index.html
> +            <div class="main-first-number">03</div>
main-first-number

2021-04-23 08:07 UTC, DenisKalyanov commented on index.html
> +            </div>
```
<div class="tab-text-mob">
       <h4>Погрузка и транспортировка</h4>
</div>
```
Если сделать 
`<h4 class="tab-text-mob">Погрузка и транспортировка</h4>` 
То ничего не поменяется, тогда зачем лишняя вложенность?

2021-04-23 08:07 UTC, DenisKalyanov commented on index.html
> +        <div class="main-second-block">
Может вообще везде избавиться от приставки `main-` в названии классов? Только удлиняет название, а смысла то...

2021-04-23 08:07 UTC, DenisKalyanov commented on index.html
> +          <div class="main-second-element">
**main-second-element** почему все **second-element** ??
Я понимаю что стили у них одинаковые, но они же не все **second-element**

2021-04-23 08:07 UTC, DenisKalyanov commented on index.html
> +              <nobr>
тут совсем не нужен этот тег. И вообще в данном проекте он не найдёт применения, потому что он заставляет скролиться всю страницу. вправо /  влево.

2021-04-23 08:07 UTC, DenisKalyanov commented on index.html
> +          <a class="main-fourth-button" href="#">Все отзывы</a>
Обоснуй, почему тут тег `<a>`.
Обосновать можно и тогда его стоит оставлять, если не сможешь обосновать тогда меняй его.
Я об этом писал в документации, просто не помню в каком это СТ.

2021-04-23 11:31 UTC, slver-dragon commented on css/style.css
> +        margin-right: auto;
Поправил, ближе к середине этого задания я уже и сам пришел к использованию исправленного margin, хотя то, что при auto верх и низ принимается за ноль не знал, буду иметь ввиду.

2021-04-23 11:48 UTC, slver-dragon commented on css/style.css
> +        width: 81.5625rem;
Полностью избавился от задания ширины и высоты, а также от центрирования посредством margin, сделал центрирование силами flex. Скажем так, меня смущало то, что без задания ширины блок старается занять все доступное пространство.

2021-04-23 11:54 UTC, slver-dragon commented on index.html
> +              <p>Переезд за 4 часа</p>
На мой взгляд нельзя, поскольку класс trans (transportation) распределяет элементы через flex

2021-04-23 11:56 UTC, slver-dragon commented on index.html
> +            <div class="trans" >
Выше пояснил причину такого оформления

2021-04-24 08:34 UTC, slver-dragon commented on index.html
> +              <p>Переезд за 4 часа</p>
Да, поправил.

2021-04-24 11:43 UTC, slver-dragon commented on index.html
> +            <div class="trans" >
Удалил за ненадобностью.

2021-04-25 14:45 UTC, slver-dragon commented on index.html
> +            <h1>100 руб.</h1>
Переработал.

2021-04-25 14:45 UTC, slver-dragon commented on index.html
> +        <h1>Автопарк</h1>
Переработал.

2021-04-25 14:46 UTC, slver-dragon commented on index.html
> +          <a href="#" class="main-third-back">&lt;</a>
Я использую вместо картинки символ меньше.

2021-04-25 14:48 UTC, slver-dragon commented on index.html
> +              <h2>Ирина</h2>
Имя выступает как заголовок в комментарии.

2021-04-25 14:50 UTC, slver-dragon commented on index.html
> +              <a class="read-after" href="#">Читать полностью</a>
Так оно же должно давать полный обзор. Как я понимаю осуществляем переход к полной версии.

2021-04-25 14:53 UTC, slver-dragon commented on index.html
> +              <nobr>
Почему? Я просто блокирую возврат каретки, группируя дату и звездочки.

2021-04-25 14:54 UTC, slver-dragon commented on index.html
> +              <h2>Ольга Петрова</h2>
Я уже писал выше, что для отзыва имя выступает как заголовок.

2021-04-25 14:55 UTC, slver-dragon commented on index.html
> +              <a class="read-after" href="#">Читать полностью</a>
Если на это будет "вешаться" какая-нибудь другая обработка, тогда да.

2021-04-25 15:01 UTC, slver-dragon commented on css/style.css
> +        padding: .495rem 4.8125rem;
Такая запись допустима http://htmlbook.ru/samcss/znacheniya-stilevykh-svoystv

2021-04-25 16:30 UTC, slver-dragon commented on css/style.css
> +        position: absolute;
Переделал.

2021-04-25 16:33 UTC, slver-dragon commented on css/style.css
> +        width: 69.125rem;
Переделал, избавился от фиксированных размеров, остались только процентные размеры.

2021-04-25 16:34 UTC, slver-dragon commented on css/style.css
> +        margin: 0% 0% 5%;
Марджин переделан.

2021-04-25 16:42 UTC, slver-dragon commented on css/style.css
> +        margin-right: auto;
Сгруппировал.

2021-04-25 16:42 UTC, slver-dragon commented on css/style.css
> +        width: 120rem;
Избавился от фиксированных размеров.

2021-04-25 16:43 UTC, slver-dragon commented on css/style.css
> +        width: 26.3125rem;
Переделал избавившись от фиксированных размеров.

2021-04-25 16:44 UTC, slver-dragon commented on css/style.css
> +        height: .125rem;
Ок.

2021-04-25 16:51 UTC, slver-dragon commented on css/style.css
> +        width: 26.25rem;
Избавился от фиксированной ширины

2021-04-25 16:54 UTC, slver-dragon commented on css/style.css
> +        margin: .625rem 0rem 1.1875rem;
Ок

2021-04-25 17:09 UTC, slver-dragon commented on css/style.css
> +
переделал

2021-04-25 17:11 UTC, slver-dragon commented on index.html
> +        <h1>Как это происходит?</h1>
Избавился от лишних

2021-04-25 17:13 UTC, slver-dragon commented on index.html
> +            <div class="main-first-number">01</div>
Переделал

2021-04-25 17:50 UTC, slver-dragon commented on index.html
> +          <div class="main-first-element">
А что не так, есть однотипные flex блоки, в которые вложено два элемента, число и текст.

2021-04-25 17:53 UTC, slver-dragon commented on index.html
> +            </div>
Поправил

2021-04-25 17:55 UTC, slver-dragon commented on index.html
> +        <div class="main-second-block">
на данный момент избавляться это приличный кусок правки, и не факт что сразу все вычищу, лучше оставить, в другом проекте, если будет постараюсь получше систему придумать.

2021-04-26 07:41 UTC, slver-dragon commented on index.html
> +            </div>
Избавился от лишнего.

2021-04-26 07:46 UTC, slver-dragon commented on index.html
> +        <div class="main-second-block">
Понимаю, но в этот раз уже оставлю. В другой раз постараюсь более удобную систему именования организовать.

2021-04-26 07:51 UTC, slver-dragon commented on index.html
> +              <nobr>
Так он не всю страницу скролит, а только вложенный текст. Я же как раз и избавляюсь от возврата каретки.

2021-04-26 08:23 UTC, slver-dragon commented on index.html
> +          <a class="main-fourth-button" href="#">Все отзывы</a>
Исправил.

2021-04-26 08:24 UTC, slver-dragon commented on index.html
> +          <div class="main-second-element">
Здесь не совсем понял вопрос.

2021-04-26 08:25 UTC, slver-dragon commented on index.html
> +          <div class="main-first-element">
Ответ выше

2021-04-26 08:25 UTC, slver-dragon commented on index.html
> +            <div class="main-first-number">02</div>
Ответ выше

2021-04-26 08:25 UTC, slver-dragon commented on index.html
> +            <div class="main-first-number">03</div>
Ответ выше

2021-04-26 08:27 UTC, slver-dragon commented on index.html
> +              <p>Стоимость переезда зависит от количества<br>комнат, вещей и мебели.</p>
Здесь у меня не очень получается, стараюсь не использовать фиксированных размеров и в итоге все "плавает".

2021-04-26 11:26 UTC, DenisKalyanov requested changes

2021-04-26 11:26 UTC, DenisKalyanov commented on index.html
> +          <span class="mid-text-mob">Отзывы</span>
А вот это могло бы претендовать на заоловок

2021-04-26 14:04 UTC, DenisKalyanov requested changes

2021-04-26 14:04 UTC, DenisKalyanov commented on index.html
> +        <span class="mid-text-mob">Цены</span>
`<span class="mid-text-mob">`Цены`</span>`
Почему ты сделал для этого отдельный span?

2021-04-26 14:04 UTC, DenisKalyanov commented on index.html
> +            <pre>1 газель - 3 метра<br>2 грузчика<br>Переезд за 4 часа</pre>
В чём особенность тега `<pre>`?

2021-04-26 14:04 UTC, DenisKalyanov commented on index.html
> +            <a href="#" class="offer-button">Заказать</a>
Даже в классе у тебя есть имя button, так может всё таки лучше использовать  button?

2021-04-26 14:04 UTC, DenisKalyanov commented on index.html
> +          <a href="#" class="element-back">&lt;</a>
Ещё раз прошу прочитать тот момент в теории когда использовать тег `a`, а когда `button`

2021-04-26 14:04 UTC, DenisKalyanov commented on index.html
> +          <a href="#" class="element-forward">&gt;</a>
Ещё раз прошу прочитать тот момент в теории когда использовать тег `a`, а когда `button`

2021-04-26 14:04 UTC, DenisKalyanov commented on index.html
> +          <a class="review-button" href="#">Все отзывы</a>
Ещё раз прошу прочитать тот момент в теории когда использовать тег `a`, а когда `button`, а возможно даже `span`

2021-04-26 14:04 UTC, DenisKalyanov commented on index.html
> +        <span class="mid-text-mob">Автопарк</span>
Зачем отдельный `span `для мобильной версии?

2021-04-26 14:04 UTC, DenisKalyanov commented on index.html
> +            <a href="#" class="offer-button">Заказать</a>
лучше `button`

2021-04-26 14:04 UTC, DenisKalyanov commented on index.html
> +        <a href="#" class="offer-allprices">Все цены</a>
лучше `button`

2021-04-26 14:04 UTC, DenisKalyanov commented on css/style.css
> +        line-height:3.5;
3.5 чего?

2021-04-26 14:04 UTC, DenisKalyanov commented on css/style.css
> +        right: 0rem;
right & bottom работают только со свойством position

2021-04-26 14:04 UTC, DenisKalyanov commented on css/style.css
> +        margin-right: auto;
Зачем  это?

2021-04-26 14:04 UTC, DenisKalyanov commented on css/style.css
> +        /*text-decoration: underline;*/
`/*text-decoration: underline;*/`

2021-04-26 14:10 UTC, slver-dragon commented on index.html
> +        <span class="mid-text-mob">Цены</span>
Для мобильной и десктопной версии различные размеры шрифтов.  Хотя если применить заголовок 2 уровня... Переделаю.

2021-04-26 16:44 UTC, slver-dragon commented on css/style.css
> +        /*text-decoration: underline;*/
Снова забыл удалить. Сделано.

2021-04-26 16:53 UTC, slver-dragon commented on css/style.css
> +        margin-right: auto;
Удалил, видимо недостаточно очистил после, "зачистки" фиксированных размеров.

2021-04-26 16:58 UTC, slver-dragon commented on css/style.css
> +        right: 0rem;
Недостаточно зачистил "остатки". Переделал.
.transport-picture {
        display: block;
    }

2021-04-26 16:59 UTC, slver-dragon commented on css/style.css
> +        line-height:3.5;
3.5 размера шрифта.

2021-04-26 17:11 UTC, slver-dragon commented on index.html
> +        <span class="mid-text-mob">Цены</span>
После ликвидации h1 не додумался сразу заголовки сместить на 1 уровень. Пришлось подгонять различные размеры шрифтов десктопной и мобильной версии. Исправил.

2021-04-26 17:12 UTC, slver-dragon commented on index.html
> +        <span class="mid-text-mob">Автопарк</span>
Аналогично первому комментарию. Исправил.

2021-04-26 17:51 UTC, slver-dragon commented on index.html
> +            <a href="#" class="offer-button">Заказать</a>
Поправил.

2021-04-27 07:07 UTC, slver-dragon commented on index.html
> +          <a href="#" class="element-back">&lt;</a>
Поправил

2021-04-27 07:08 UTC, slver-dragon commented on index.html
> +          <a href="#" class="element-forward">&gt;</a>
Заменил

2021-04-27 07:56 UTC, slver-dragon commented on index.html
> +          <a class="review-button" href="#">Все отзывы</a>
Заменил

2021-04-27 07:56 UTC, slver-dragon commented on index.html
> +            <a href="#" class="offer-button">Заказать</a>
Заменил

2021-04-27 07:56 UTC, slver-dragon commented on index.html
> +        <a href="#" class="offer-allprices">Все цены</a>
Заменил

2021-04-27 10:43 UTC, slver-dragon commented on index.html
> +            <pre>1 газель - 3 метра<br>2 грузчика<br>Переезд за 4 часа</pre>
Дейсивительно, теперь он не нужен. Заменил на span

2021-04-27 11:23 UTC, DenisKalyanov requested changes

2021-04-27 11:23 UTC, DenisKalyanov commented on index.html
> +              <p>Упаковываем вещи в коробки, подписываем.<br>Габаритное и деликатное, упаковываем<br>отдельно.</p>
`<br>` тут не нужно нигде br, позволь строке переноситься когда ей захочется в зависимости от ширины блока.

2021-04-27 11:23 UTC, DenisKalyanov commented on index.html
> +            <span class="possib">1 фургон<br>2 грузчика<br>Переезд за 4 часа</span>
Эдуард, я же писал, что ты можешь ознакомиться с тем как работает тег `<pre>` и всё сделать с помощью его. А ты вместо этого его взял и заменил)

2021-04-27 11:23 UTC, DenisKalyanov commented on index.html
> +                <span class="review-star">&#9733;&#9733;&#9733;&#9733;&#9733;</span>
у этих звёздочек есть один минус. Они непрактичны. 
Что мы будем делать если рейтинг составит 4,5 звезды?
Как мы нарисуем половину звезды жёлтой а половину черной или серой?

2021-04-27 11:23 UTC, DenisKalyanov commented on css/style.css
> +        position: absolute;
Переделал но не удалил?

2021-04-27 11:23 UTC, DenisKalyanov commented on css/style.css
> +    .offer-element-mob pre {
Но у тебя же нету тега `pre`

2021-04-27 11:23 UTC, DenisKalyanov commented on css/style.css
>          z-index: 1;
Если удалили св-во position, то и z-index удаляй

2021-04-27 11:43 UTC, slver-dragon commented on index.html
> +              <p>Упаковываем вещи в коробки, подписываем.<br>Габаритное и деликатное, упаковываем<br>отдельно.</p>
Поправил.

2021-04-27 12:31 UTC, slver-dragon commented on index.html
> +            <span class="possib">1 фургон<br>2 грузчика<br>Переезд за 4 часа</span>
Сделал через pre, хотя визуально мне не очень.

2021-04-27 12:45 UTC, slver-dragon commented on css/style.css
> +    .offer-element-mob pre {
Уже нету, остался задублированный блок.

2021-04-27 12:47 UTC, slver-dragon commented on css/style.css
>          z-index: 1;
Виноват, недоследил.

2021-04-27 13:02 UTC, slver-dragon commented on index.html
> +                <span class="review-star">&#9733;&#9733;&#9733;&#9733;&#9733;</span>
Денис, должен заметить, что отзыв не может быть дробным. Общий результат может быть дробным, но само голосование целочисленно. Хотя если необходимо, могу переделать под картинки. И целую и полузвезду уже подготовил.

2021-04-27 19:59 UTC, DenisKalyanov requested changes

2021-04-27 19:59 UTC, DenisKalyanov commented on css/style.css
> +        display: flex;
display: block;
display: flex;

Ну надо определиться

2021-04-27 19:59 UTC, DenisKalyanov commented on css/style.css
> +        position: absolute;
зачем тут position: absolute; ?

2021-04-27 19:59 UTC, DenisKalyanov commented on css/style.css
> +        align-content: center;
align-items: flex-start;
align-content: center;

Тут точно нужны эти 2 свойства?

2021-04-27 20:26 UTC, slver-dragon commented on css/style.css
> +        display: flex;
Вот блин, как это я.

2021-04-27 20:41 UTC, slver-dragon commented on css/style.css
> +        position: absolute;
без absolute картинка убегает вниз

2021-04-27 20:49 UTC, slver-dragon commented on css/style.css
> +        align-content: center;
Честно не помню откуда прицепил их.

2021-04-27 20:50 UTC, merged