feature/CT-4: -start
slver-dragon/Starter pull request #5
Opened 2021-05-03 09:20 UTC by slver-dragon

Вот что-то такое вышло.

2021-05-03 09:29 UTC, DenisKalyanov requested changes

2021-05-03 09:29 UTC, DenisKalyanov commented on index.html
> +                <label for="region"><h2> Укажите область</h2></label><br>
Нам не нужно в label вкладывать тег h2.

2021-05-03 09:29 UTC, DenisKalyanov commented on index.html
> +                <input type="tel" placeholder="Телефон" id="phone"><br>
Мы вообще не будем по возможности использовать id="" в label и input.
Потом этот атрибут нам понадобиться для других целей.

2021-05-03 09:43 UTC, slver-dragon commented on index.html
> +                <label for="region"><h2> Укажите область</h2></label><br>
Поправил. Вводом класса

2021-05-03 09:43 UTC, slver-dragon commented on index.html
> +                <input type="tel" placeholder="Телефон" id="phone"><br>
Ок, удалю

2021-05-04 07:50 UTC, DenisKalyanov requested changes

2021-05-04 07:50 UTC, DenisKalyanov commented on css/style.css
> +    /*.addition-services {
давай удалим ненужные классы и комментарии.

2021-05-04 07:50 UTC, DenisKalyanov commented on index.html
> +                <input type="tel" placeholder="Телефон" id="phone"><br>
Так а чего не удалил? :)

2021-05-04 07:50 UTC, DenisKalyanov commented on index.html
> +                <label for="region" class="fname"> Укажите область</label><br>
Почему тут сделал через `label` а ниже через `span`?

2021-05-04 07:50 UTC, DenisKalyanov commented on index.html
> +                <input type="checkbox" name="crane" disabled>
disabled блокирует поля и мы не сможем ничего нажать.

2021-05-04 07:50 UTC, DenisKalyanov commented on index.html
> +                <input type="checkbox" name="assembly" checked>
checked тут не обязательно, это просто на макете показывается как отрабатывает данный чекбокс.

2021-05-04 07:50 UTC, DenisKalyanov commented on index.html
> +                <input type="checkbox" name="packing" disabled>
disabled блокирует поля и мы не сможем ничего нажать.

2021-05-04 07:50 UTC, DenisKalyanov commented on index.html
> +                <input type="radio" name="pay" value="bank" disabled>
disabled тут не нужно

2021-05-04 07:50 UTC, DenisKalyanov commented on index.html
> +                <input type="radio" name="pay" value="courier" disabled>
disabled тут не нужно

2021-05-04 07:50 UTC, DenisKalyanov commented on index.html
> +                <label><input type="checkbox" name="apply" checked><span class="apply"> Даю согласие на обработку данных</span></label>
Может быть стоит просто менять кнопку в вёрстке десктоп/мобильная. чем добавлять целый блок.
А `<span class="timer">05:37:25</span>` в мобильной версии сделать просто display: none;

Так как сделал ты тоже можно, но посмотри как это увеличивает код.

2021-05-04 07:50 UTC, DenisKalyanov commented on index.html
> +      <div class="map">
А как же карта?

2021-05-05 12:28 UTC, slver-dragon commented on css/style.css
> +    /*.addition-services {
Скажем так, это было зарезервировано под данное задание. В процессе завершения лишнее удалено.

2021-05-05 12:53 UTC, slver-dragon commented on index.html
> +                <label for="region" class="fname"> Укажите область</label><br>
Упустил, не доделал. Теперь все исправлено.

2021-05-05 12:54 UTC, slver-dragon commented on index.html
> +                <input type="checkbox" name="crane" disabled>
Я делал по образцу. Теперь все включено.

2021-05-05 12:54 UTC, slver-dragon commented on index.html
> +                <input type="checkbox" name="packing" disabled>
Исправлено

2021-05-05 12:54 UTC, slver-dragon commented on index.html
> +                <input type="radio" name="pay" value="bank" disabled>
Исправлено

2021-05-05 12:55 UTC, slver-dragon commented on index.html
> +                <input type="radio" name="pay" value="courier" disabled>
Исправлено

2021-05-05 12:55 UTC, slver-dragon commented on index.html
> +      <div class="map">
Создавал про запас

2021-05-05 13:17 UTC, slver-dragon commented on index.html
> +                <label><input type="checkbox" name="apply" checked><span class="apply"> Даю согласие на обработку данных</span></label>
Исправил.

2021-05-05 13:17 UTC, slver-dragon commented on index.html
> +                <input type="checkbox" name="assembly" checked>
Поправил

2021-05-06 07:21 UTC, DenisKalyanov requested changes

2021-05-06 07:21 UTC, DenisKalyanov commented on css/style.css
> +    	padding: 0 0 0 3rem;
Нужно выровнять, чтобы красиво отображалось.

2021-05-06 07:21 UTC, DenisKalyanov commented on css/style.css
> +
зачем тут пустое поле?

2021-05-06 07:21 UTC, DenisKalyanov commented on index.html
> +                <span class="fname">Укажите город</span><br>
fname - не информативное название класса.

2021-05-06 07:21 UTC, DenisKalyanov commented on index.html
> +              <span class="fname">Способ оплаты</span><br>
Также fname непонятное название класса. fname -  может быть всё что угодно, нужно чтобы оно описало суть самого блока.
`<br>` точно ли лучшим решением тут будет использовать этот тег? Так как span строковый элемент, то  у него нет переноса строки и ты решил воспользоваться `<br>`, но может сделать этот тег блочным?
display: block; и тогда у него появятся все методы блочного тега и перенос строки.
 `<br>` обычно используется для переноса текста, который находиться в одном теге. 
 Такой вариант как ты сделал, тоже возможен и имеет место быть, но лучше оформить это через стили.

2021-05-06 07:21 UTC, DenisKalyanov commented on index.html
> +              <li><span class="inform-city">Брест</span></li>
А зачем внутри `li` ещё и `span`? 
Лишнее нагромождение тегов. Мы прекрасно можем разместить текст внутри `li`

2021-05-06 07:21 UTC, DenisKalyanov commented on index.html
> +              <li><span class="inform-phone">8-(029)-999-12-13</span></li>
У всех элементов этого списка разные классы. Но по макету они выполнены все в одном стиле.
Может тогда не стоит создавать 3 класса, а создать только 1 и присвоить всем.

2021-05-06 07:21 UTC, DenisKalyanov commented on index.html
> +          <li><u>8 (029)-999-12-13</u></li>
http://htmlbook.ru/html/u
Вырезка из статьи:
_Этот тег осуждается спецификацией HTML, взамен рекомендуется использовать стили._

2021-05-06 07:50 UTC, slver-dragon commented on css/style.css
> +    	padding: 0 0 0 3rem;
Поправил, заодно, по аналогии и радио поправил

2021-05-06 07:57 UTC, slver-dragon commented on css/style.css
> +
не доглядел

2021-05-06 08:02 UTC, slver-dragon commented on index.html
> +                <span class="fname">Укажите город</span><br>
Сменил наименование.

2021-05-06 08:09 UTC, slver-dragon commented on index.html
> +              <span class="fname">Способ оплаты</span><br>
Согласен, переделал через div

2021-05-06 08:15 UTC, slver-dragon commented on index.html
> +              <li><span class="inform-city">Брест</span></li>
Уф... Как я такое нагромоздил? Поправил.

2021-05-06 08:21 UTC, slver-dragon commented on index.html
> +              <li><span class="inform-phone">8-(029)-999-12-13</span></li>
Виноват, снова недоглядел. В мобильной версии поправил, а десктопную "недочистил".

2021-05-06 09:18 UTC, slver-dragon commented on index.html
> +          <li><u>8 (029)-999-12-13</u></li>
Я использовал обертывание текста в span  и придал свойство именно span'y

2021-05-06 11:33 UTC, JuliaTsaruk requested changes

2021-05-06 11:33 UTC, JuliaTsaruk commented on index.html
> +                <input type="text" class="input-city" placeholder="Добавить город"><br>
Чтобы не задавать тег br, можно в стилях строчному элементу присвоить display: block.

2021-05-06 11:33 UTC, JuliaTsaruk commented on index.html
> +            </ul>
Телефон и почту можно сделать кликабельными

2021-05-06 11:33 UTC, JuliaTsaruk commented on index.html
> +        </ul>
Можно оформить без списка, как ты сделал с 322-327 строку

2021-05-06 11:33 UTC, JuliaTsaruk commented on index.html
> +              </label>
У меня на 1920 банковский перевод переносится на новую строку, а в макете все способы оплаты в одну. Проверь, пожалуйста.

2021-05-06 11:33 UTC, JuliaTsaruk commented on index.html
> +            <a href="instagram.com"><img src="/img/instagram.png" alt="#"></a>
Нерабочие ссылки на социальные сети

2021-05-06 11:33 UTC, JuliaTsaruk commented on index.html
> +          <button class="footer-button-mob">Заказать</button>
Нерабочие ссылки на социальные сети

2021-05-06 11:33 UTC, JuliaTsaruk commented on index.html
> +                <div class="form-prompt">Укажите город</div>
При уменьшении размера экрана input имя и телефон будто сливаются, тоже самое с ниспадающими списками. Выглядит не очень красиво

2021-05-06 11:33 UTC, JuliaTsaruk commented on css/style.css
>      .review-button:hover {
При нажатии на кнопку дергается весь блок.

(строки 85 - 115)
Также кнопки в секции prices, при hover имеют box-shadow (макет) и аналогичные кнопки по всему сайту.
И при уменьшении экрана кнопки в секции prices съезжают и выходят за границы блока offer-element.

2021-05-06 11:33 UTC, JuliaTsaruk commented on index.html
>     <header>
Посмотри строки 119-123,  элемент списка "Газели" активный

2021-05-06 13:47 UTC, slver-dragon commented on index.html
> +            <a href="instagram.com"><img src="/img/instagram.png" alt="#"></a>
Поправил, без указания протокола адрес не срабатывал

2021-05-06 13:49 UTC, slver-dragon commented on index.html
> +              </label>
Поправил, немного не рассчитал ширину блока.

2021-05-06 13:52 UTC, slver-dragon commented on index.html
> +        </ul>
Действительно, что-то я нагородил. Хотя скорее всего просто во втором блоке избавился от излишней нагроможденности, а в этом недосмотрел.

2021-05-06 14:06 UTC, slver-dragon commented on index.html
> +            </ul>
Не думаю, что это необходимо. Это обычное информационное окно. На мой взгляд итак достаточно ссылок для осуществления звонка и перехода к написанию писем.

2021-05-06 15:51 UTC, slver-dragon commented on index.html
> +                <input type="text" class="input-city" placeholder="Добавить город"><br>
Спасибо за совет, поправил.

2021-05-06 15:56 UTC, slver-dragon commented on index.html
> +          <button class="footer-button-mob">Заказать</button>
Тут я не вижу ссылок, но по предыдущему коммиту поправил все ссылки.

2021-05-06 16:52 UTC, slver-dragon commented on index.html
> +                <div class="form-prompt">Укажите город</div>
Поправил, с помощью размеров в %

2021-05-06 18:28 UTC, slver-dragon commented on css/style.css
>      .review-button:hover {
Дело было в изменении размеров кнопки, при удалении границы. Решил заменой цвета границы, вместо ее удаления. 

Заменил размеры кнопок и шрифтов на масштабируемые.

2021-05-06 19:15 UTC, slver-dragon commented on index.html
>     <header>
Добавил, хотя как я понимаю, оно "оживляться" будет с помощью js

2021-05-07 10:08 UTC, DenisKalyanov requested changes

2021-05-07 10:08 UTC, DenisKalyanov commented on css/style.css
> +        font-size: 1vw;
И какой будет размер текста?
vw это ширина экрана.

2021-05-07 10:08 UTC, DenisKalyanov commented on css/style.css
> +    /*форма заказа*/
Удаляем комментарии.

2021-05-07 10:08 UTC, DenisKalyanov commented on css/style.css
> + /* Checked-radio*/
Удаляем комментарии, название класса и так говорит само за себя

2021-05-07 10:08 UTC, DenisKalyanov commented on css/style.css
> +    	margin-right: 0.75rem;
Пляшет форматирование стилей.

2021-05-07 10:08 UTC, DenisKalyanov commented on css/style.css
> +    	padding: 0 0 0 3rem;
Я имел в виду отформатировать код, чтобы отстуры от края были одинаковые.
И почему у тебя перед селектором по 4 пробела. Код должен прилегать к левой стенке.
![image](https://user-images.githubusercontent.com/57324793/117433027-afa5be80-af33-11eb-9351-2acb47ba01e7.png)

2021-05-07 10:08 UTC, DenisKalyanov commented on index.html
>     <header>
Юля права, активный элемент всё равно должен выделяться. Если у нас показывается газель, то логично, что и кнопка с газелью должна быть выделена.

2021-05-07 10:08 UTC, DenisKalyanov commented on index.html
> +          <span class="noactive">Грузовики</span>
весьма не информативный класс. Что за "актив" и "не активный". Таким может быть любой элемент на странице, у нас тут что, типо автомобиля? Значит:

```
<span class="car-type active">Газели</span>
<span class="car-type">Каблуки</span>
<span class="car-type">Грузовики</span>
```

2021-05-07 10:08 UTC, DenisKalyanov commented on index.html
> +              <li>8-(029)-999-12-13</li>
Неплохо было бы сделать, чтобы номер мог набираться по нажатию.

2021-05-07 10:08 UTC, DenisKalyanov commented on index.html
> +          <button class="footer-button-mob">Заказать</button>
Это Юля написала к тому, потому что хочет чтобы ты уже быстрее подключал JavaScript и сделал ссылки рабочими :)

2021-05-07 11:29 UTC, slver-dragon commented on css/style.css
> +        font-size: 1vw;
Согласен, более точное значение будет 1.042vw. Исправил.

2021-05-07 11:29 UTC, slver-dragon commented on css/style.css
> +    /*форма заказа*/
Удалил.

2021-05-07 11:32 UTC, slver-dragon commented on css/style.css
> + /* Checked-radio*/
Все комментарии удалил.

2021-05-07 11:47 UTC, slver-dragon commented on index.html
> +          <span class="noactive">Грузовики</span>
Поправил все

2021-05-07 12:03 UTC, slver-dragon commented on index.html
> +              <li>8-(029)-999-12-13</li>
Сделал раз нужно. Это элементарно.

2021-05-07 15:30 UTC, merged