feature/CT-5: -probe...
slver-dragon/Starter pull request #6
Opened 2021-05-12 08:14 UTC by slver-dragon

2021-05-14 09:02 UTC, DenisKalyanov requested changes

2021-05-14 09:02 UTC, DenisKalyanov commented on index.html
> +            </script>
Этот скрипт от сюда убираем. В документ со скриптами.

2021-05-14 09:02 UTC, DenisKalyanov commented on index.html
> +              let addition_service = document.getElementById("addition-service");
Давай будем использовать camelCase. 
Это стиль наименования переменных.
Называется Верблюжий стиль, в чем его смысл, в том, что addition_service превратиться в additionService

2021-05-14 09:02 UTC, DenisKalyanov commented on index.html
> +                if (addition_service.hidden != true) {
Кстати попробуй воспользоваться в решении этой задачки 
classList.toggle
Вот тут можно потренироваться:
https://htmlacademy.ru/courses/343/run/10

Решение будет в одну строку кода.

2021-05-14 09:02 UTC, DenisKalyanov commented on scripts/script.js
> +    /*submit*/
Очень больше решение и куча непонятных строк кода.
Нам по сути что нужно сделать. При отправке формы submit, нужно запустить функцию в которой мы получим значение полей, если поля не пустые то ОК, если есть пустое поле, форма не отправляется, а пустое поле выделяется красным border.

2021-05-14 09:02 UTC, DenisKalyanov commented on scripts/script.js
> +  this.value = this.value.replace(not_valid_num, "");
Что ты тут валидируешь?
Мы должны валидировать только ИМЯ и ТЕЛЕФОН. Строка для ввод города не обязательно. Так как пользователь может быть из Бреста, тогда зачем ему вводить город, если такой уже имеется в списке. 
Прочитай ещё раз ТЗ.

2021-05-14 09:02 UTC, DenisKalyanov commented on scripts/script.js
> +
Валидацию делаем отельной частью документа JS.
А добавление города так е отдельной частью, не стоит все реализации писать водной куче. Сделал какую-то функцию, дал 2 переноса строки, объявил новые переменные и написал ещё один обработчик.

2021-05-14 09:02 UTC, DenisKalyanov commented on scripts/script.js
> +  --period;
Видать решение скопировано из интернета, может у ребят. Я надеюсь, что ты разобрался как это работает. 
С чего я сделал такой вывод? С того что тут у тебя переменные в camelCase

2021-05-14 09:02 UTC, DenisKalyanov commented on scripts/script.js
> +  minutes = minutes < 10 ? "0" + minutes : minutes;
Тут ошибки нет, но посмотри просто как работает тернарный опператор.
В кратце:
условие ? true : false
Как он у нас работает, есть условие, после его мы пишем вопросительный знак. 
Если условие выполняется мы получаем значение до двоеточия, если не выполняется то на выходе имеем значение после двоеточия. 

Это я написал на тот случай, если ты скопировал код и не совсем понял что тут произошло.

2021-05-14 09:09 UTC, slver-dragon commented on index.html
> +            </script>
Забыл убрать, он уже перенесен в отдельный файл. Убрал.

2021-05-14 09:17 UTC, slver-dragon commented on scripts/script.js
> +  this.value = this.value.replace(not_valid_num, "");
Я просто блокирую ввод цифр в полях Фамилии и Города. Это, так сказать, своя придумка.

2021-05-14 09:26 UTC, slver-dragon commented on index.html
> +              let addition_service = document.getElementById("addition-service");
Переделал все, надеюсь речь шла только о JS

2021-05-14 09:34 UTC, slver-dragon commented on scripts/script.js
> +  --period;
Решение подсмотрено в интернете, тем не менее код не простая копипаста, а адаптация под ситуацию ну и под влиянием исходника остался camelCase. (в исходнике был оформлен с двумя датами таймер)

2021-05-14 09:35 UTC, slver-dragon commented on scripts/script.js
> +  minutes = minutes < 10 ? "0" + minutes : minutes;
Данный код точно самописный. Уж очень резали глаза "одноместные" числаю

2021-05-14 10:49 UTC, slver-dragon commented on index.html
> +                if (addition_service.hidden != true) {
Не понимаю в чем здесь может быть экономия.

2021-05-14 11:48 UTC, slver-dragon commented on scripts/script.js
> +    /*submit*/
Разделил.

2021-05-14 12:13 UTC, slver-dragon commented on scripts/script.js
> +
Разделил.

2021-05-17 09:08 UTC, DenisKalyanov requested changes

2021-05-17 09:08 UTC, DenisKalyanov commented on scripts/script.js
> +  //блокирование цифр в текстовом поле Имя
Вот давай вообще без комментариев. А то это очень плохо.

2021-05-17 09:08 UTC, DenisKalyanov commented on scripts/script.js
> +let elementForward = document.getElementById("elementForward");
Переделай слайдер. 
1. Это не самое оптимальное решение.
2. Но даже и это решение можно оптимизировать, но тут нужно кардинально изменять структуру, чтобы сохранить ту же логику, что ты предлагаешь.

2021-05-17 09:08 UTC, DenisKalyanov commented on scripts/script.js
> +  addition_service.hidden = addition_service.hidden != true;
Почему тут тоже не использовать classList.toggle

2021-05-17 09:08 UTC, DenisKalyanov commented on scripts/script.js
> +    form.submit();
используй в собитиях формы e.preventDefault 
Это отменит стандартные обработчики в браузере (а самое главное отменит обновление страницы при отправке формы)

2021-05-17 09:08 UTC, DenisKalyanov commented on scripts/script.js
> +};
Пользователь надеется, что при добавлении города он нажмёт Enter  и всё что произойдёт, это добавление города. Но как я понимаю, у нас сработает отправка формы, страница обновится, а если он не заполнил поля то ещё и выскочит валидация. А он просто хотел добавить свой город.

2021-05-17 09:17 UTC, DenisKalyanov requested changes

2021-05-17 09:17 UTC, DenisKalyanov commented on scripts/script.js
> +let hider_button = document.getElementById("hider-button");
camelCase

2021-05-17 09:17 UTC, DenisKalyanov commented on scripts/script.js
> +  yourName.className = "your-name";
Это функция вообще для чего?
Если для того, чтобы убрать красное выделение, то может воспользоваться удалением класса.

2021-05-17 09:17 UTC, DenisKalyanov commented on scripts/script.js
> +  yourName.placeholder = "Ваше имя";
Ты добавляешь повторно placeholder. хотя он у тебя и так должен там быть.

2021-05-17 09:17 UTC, DenisKalyanov commented on scripts/script.js
> +orderButton.onclick = function () {
используй e.preventDefault он предотвратит постоянное обновление страницы при отправки формы

2021-05-17 09:17 UTC, DenisKalyanov commented on scripts/script.js
> +  if (!apply.checked) {
Кстати условия можно объединять с помощью ?? (и), || (или)

2021-05-17 09:31 UTC, slver-dragon commented on scripts/script.js
> +let hider_button = document.getElementById("hider-button");
Поправил

2021-05-17 09:37 UTC, slver-dragon commented on scripts/script.js
> +  addition_service.hidden = addition_service.hidden != true;
Я решил не добавлять новые классы если можно просто командой скрывать блок, в отличии от стрелочки, которую не просто скрываем, а меняем форму.

2021-05-17 09:37 UTC, slver-dragon commented on scripts/script.js
> +  //блокирование цифр в текстовом поле Имя
Вычистил комментарии

2021-05-17 09:48 UTC, slver-dragon commented on scripts/script.js
> +    form.submit();
Добавил. Буду теперь знать.

2021-05-17 09:50 UTC, slver-dragon commented on scripts/script.js
> +};
Решил добавлением event.preventDefault().

2021-05-17 09:53 UTC, slver-dragon commented on scripts/script.js
> +  yourName.placeholder = "Ваше имя";
Я возвращаю исходный. При смене класса, placeholder меняется на подсказку причины ошибки "Нет имени" и "Не указан номер".

2021-05-17 09:53 UTC, slver-dragon commented on scripts/script.js
> +orderButton.onclick = function () {
Поправил.

2021-05-17 10:20 UTC, slver-dragon commented on scripts/script.js
> +  if (!apply.checked) {
Согласен, не подумал. Объединил два условия в одно.

2021-05-17 10:22 UTC, slver-dragon commented on scripts/script.js
> +  yourName.className = "your-name";
Возвращаю предыдущий класс и плейсхолдер. В следующем комменте более подробно описание ситуации.

2021-05-17 11:26 UTC, slver-dragon commented on scripts/script.js
> +let elementForward = document.getElementById("elementForward");
Изменил ориентацию массива, добавил возможность работы с иным числом элементов (большим чем 3)

2021-05-18 08:04 UTC, DenisKalyanov requested changes

2021-05-18 08:04 UTC, DenisKalyanov commented on scripts/script.js
> +    if (event.keyCode == 13) {
Сейчас по-моему актуальней писать .code

2021-05-18 08:04 UTC, DenisKalyanov commented on scripts/script.js
> +    form.submit();
Удаляй это и вызывай вообще обработчик form.onsubmit или addEventListener('onsubmin', /)
и внутри этого пиши всю логику

2021-05-18 08:04 UTC, DenisKalyanov commented on scripts/script.js
> +      event.preventDefault();
preventDefault просто предотвратит обновление страницы. Но всё равно так как этот инпут находиться внутри формы, сработает submit у формы, считай та же отправка формы, но без обновления страницы. Поэтому ты не добавляешь город а пытаешься отправить форму

2021-05-18 08:04 UTC, DenisKalyanov commented on scripts/script.js
> +orderButton.onclick = function () {
вся проблема что правильно будет обрабатывать onsubmin, а не onclick

2021-05-18 08:54 UTC, DenisKalyanov requested changes

2021-05-18 08:54 UTC, DenisKalyanov commented on scripts/script.js
> +};
не решил.

2021-05-18 12:30 UTC, slver-dragon commented on scripts/script.js
> +      event.preventDefault();
Избавился от необходимости введения ограничений выведя данное поле из формы

2021-05-20 10:45 UTC, slver-dragon commented on scripts/script.js
> +    if (event.keyCode == 13) {
Поправил

2021-05-20 10:45 UTC, slver-dragon commented on scripts/script.js
> +    form.submit();
Переделал

2021-05-20 10:46 UTC, slver-dragon commented on scripts/script.js
> +      event.preventDefault();
Переделал

2021-05-20 14:43 UTC, DenisKalyanov requested changes

2021-05-20 14:43 UTC, DenisKalyanov commented on scripts/script.js
> +  for (let i = 1; i < 6; i++) {
что такое 6? 
Не до конца универсальный код.

arr.length -1

2021-05-20 14:43 UTC, DenisKalyanov commented on scripts/script.js
> +  yourName.value == '' || yourPhon.value == '' || !apply.checked ? event.preventDefault() : form.submit();
event.preventDefault() Совсем неправильный смысл ты вкладываешь в эту функцию, Или может подразумевал одно но написал не верно. 
Тут ты написал условие: Если есть пустые значения, то event.preventDefault ОТМЕНИТЬ СТАНДАРТНОЕ ПОВЕДЕНИЕ БРАУЗЕРА. Зачем такая развязка? Это мы делаем при отправке формы например. прописываем такое условие просто чтобы НЕ ОБНОВЛЯЛАСЬ СТРАНИЦА. Это всё, что на данный момент нам даёт event.preventDefault

2021-05-20 14:43 UTC, DenisKalyanov commented on scripts/script.js
> +  yourName.value == '' ? yourName.classList.add('error') : yourName.classList.remove('error');
Вынести эти 2 строчки с проверкой на пустое поле, в отдельную функцию 
function validate(){
1.
2.
}

А после вызывай эту функцию в том месте где нужно произвести вариацию

2021-05-20 14:43 UTC, DenisKalyanov commented on scripts/script.js
> +};
yourName.oninput = () => yourName.classList.remove("error");

Стоит вернуть обработчик  oninput, НО НЕ ВНУТРИ Какой-то функции, просто чтобы он срабатывал где-то отдельно, можешь его написать сразу после объявления переменных. При чём их должно быть 2 на какое поле; Просто я говорил удалить, только самодеятельность связанную с добавлением плейсхолдера и стандартного класса

2021-05-20 14:43 UTC, DenisKalyanov commented on scripts/script.js
> +  form.addEventListener("keydown", function (levent) {
так ты вроде для  input делаешь эту функцию, с добавлением города. А обработчик вешаешь на from
И что за levent?? Это и есть твоё событие event.
event.code
event.target
event.preventDefault
 и т.д.

2021-05-20 14:55 UTC, slver-dragon commented on scripts/script.js
> +  yourName.value == '' ? yourName.classList.add('error') : yourName.classList.remove('error');
Сделал.

2021-05-20 16:29 UTC, slver-dragon commented on scripts/script.js
> +  for (let i = 1; i < 6; i++) {
Поправил, за одним исключением, там у меня перебирается содержимое элемента массива, поэтому transport[0].length-1

2021-05-20 16:54 UTC, slver-dragon commented on scripts/script.js
> +};
Сделал, но ты вероятно ошибся данный обработчик у меня висел на onfocus, на oninput у меня висел контроль ввода символов.

2021-05-21 10:24 UTC, slver-dragon commented on scripts/script.js
> +  form.addEventListener("keydown", function (levent) {
Все исправил, проблема была в том, что event.code принимает значение "Enter", а не 13.

2021-05-21 10:24 UTC, slver-dragon commented on scripts/script.js
> +  yourName.value == '' || yourPhon.value == '' || !apply.checked ? event.preventDefault() : form.submit();
Сделано.

2021-05-21 13:39 UTC, DenisKalyanov requested changes

2021-05-21 13:39 UTC, DenisKalyanov commented on scripts/script.js
> +  console.log(event.code);
удаляем console.log

2021-05-21 13:39 UTC, DenisKalyanov commented on scripts/script.js
> +  if (event.code == 'Enter') {
тут тебе по сути не важно вообще, нажат ли Enter  или нет, мы в любом случае отменяем отправку. Так что можно preventDefault просто вынести из условия.  А на Enter просто поставить обработку события.

2021-05-21 14:25 UTC, slver-dragon commented on scripts/script.js
> +  if (event.code == 'Enter') {
Почистил.

2021-05-21 14:26 UTC, slver-dragon commented on scripts/script.js
> +  console.log(event.code);
Удалил, это вроде как проверочный был, в любом случае перед слиянием зачистил бы.

2021-05-24 09:11 UTC, merged