Feature/ct 5
slver-dragon/Starter pull request #7
Opened 2021-05-25 11:16 UTC by slver-dragon

2021-05-28 22:42 UTC, DenisKalyanov requested changes

2021-05-28 22:42 UTC, DenisKalyanov commented on index.html
> +              <i></i>
tri-line? 
давай уже сразу  tri-linii )
чтобы в такие моменты было меньше хлопот, лучше сразу вставить svg элемент. При нажатии меняешь его на другой svg (если ты хочешь его менять на крестик)

2021-05-28 22:42 UTC, DenisKalyanov commented on index.html
> +            </ul>
Хочешь сделать круто? 
Можешь сделать это якорными ссылками. Почитай что это. 
Так как у нас. на данный момент все эти блоки есть на странице и не ведут никуда дальше, то самое то

2021-05-28 22:42 UTC, DenisKalyanov commented on index.html
> +            alt="Газели"
почему именно газели?
если id="transport-picture" так это картинка именно газели или любого транспорта. Если любого то в альт тоже должен быть написан транспорт

2021-05-28 22:42 UTC, DenisKalyanov commented on scripts/script.js
> +};
Что же ты натворил)
Это чтобы добавить рамку элементу? А как на счёт использовать в css Псевдокласс :hover

2021-05-28 22:42 UTC, DenisKalyanov commented on scripts/script.js
> +tekElement1.onclick = function () {
tekElement1. tekElement2 tekElement3
Что на счёт делегирования событий? Мы же можем получить текущий элемент и провести действие над ним. 
Или другим способом получать элемент на котором произошло событие и навести на его обработчик.

2021-05-28 22:42 UTC, DenisKalyanov commented on scripts/script.js
>    document.getElementById(transport[current][0]).className = "car-type";
ты присваиваешь первому (выбранному изначально элементу) обычный класс. Но он у него должен быть сразу. А вот car-type-active нужно добавлять уже в самом JS, исходя из того какой элемент выбран. Изначально это первый элемент. А может и 2 изначально, смотря что ты захочешь.

2021-05-28 22:42 UTC, DenisKalyanov commented on scripts/script.js
> +  triLine.classList.length == 1
при чём тут эта логика?
Это по сути работает так же как и показать/скрыть блок "Дополнительные услуги" 
Нажал кнопку блок показался нажал ещё раз, блок удалился и так до бесконечности.

2021-05-29 14:23 UTC, slver-dragon commented on index.html
> +              <i></i>
Все-таки сделал через треугольник-стрелкую

2021-05-29 14:37 UTC, slver-dragon commented on index.html
> +            </ul>
Сделал.

2021-05-29 14:39 UTC, slver-dragon commented on index.html
> +            alt="Газели"
Согласен, нужно было поправлять на этапе создания слайдера. Исправил.

2021-05-29 14:45 UTC, slver-dragon commented on scripts/script.js
> +};
Мдя. Перестарался. :)
Поправил.

2021-05-29 14:50 UTC, slver-dragon commented on scripts/script.js
> +  triLine.classList.length == 1
В данном случае у меня tri-line, "подскакивал" немного и добавив к нему еще один класс я возвращал его на необходимый уровень.
Сейчас же, после внесения изменений, видоизмененное условие меняет внешний вид "бургера".

2021-05-29 14:59 UTC, slver-dragon commented on scripts/script.js
>    document.getElementById(transport[current][0]).className = "car-type";
Поправил, хотя размер кода слегка увеличился, но, возможно, стал понятнее и читабельнее.

2021-05-30 15:55 UTC, slver-dragon commented on scripts/script.js
> +tekElement1.onclick = function () {
Сделал. Повозиться пришлось, но получилось. Вот такого совета я и ждал, когда в первый раз советовался по поводу однотипных функций.

2021-05-31 08:11 UTC, DenisKalyanov requested changes

2021-05-31 08:11 UTC, DenisKalyanov commented on index.html
> +              <i></i>
Этот комментарий был к названию класса. Что за tri?

2021-05-31 08:11 UTC, DenisKalyanov commented on index.html
> +                value=" "
Это значит что поле не пустое и там есть пробел.

2021-05-31 08:11 UTC, DenisKalyanov commented on scripts/script.js
> +  isNaN(newEl) ? newEl = current : current = newEl;
newEl может быть не числом? Ты проверяешь на isNaN, но вроде у тебя везде математические опперации.

2021-05-31 08:11 UTC, DenisKalyanov commented on scripts/script.js
> +let triLine = document.getElementById("tri-line");
threeLine Если на то пошло. А так это burgerMenu

2021-05-31 08:11 UTC, DenisKalyanov commented on scripts/script.js
> +    : triLine.className = "tri-line";
elem.classList.add/remove("class")
Ты это имел ввиду?

2021-05-31 08:11 UTC, DenisKalyanov commented on scripts/script.js
> +  elementReplace(Number(targetElement.slice(5,targetElement.length)) - 1);
Так, что тут происходит?
Ты хочешь получить последний элемент строки?
charAt можешь использовать или
targetElement.slice(-1)

2021-05-31 10:10 UTC, slver-dragon commented on index.html
> +                value=" "
Переименовал в three-line и threeLine. 

Не помню почему я там поставил пробел.

2021-05-31 10:12 UTC, slver-dragon commented on scripts/script.js
> +  isNaN(newEl) ? newEl = current : current = newEl;
Денис, при нажатии вне зоны полей захватывает NaN.

2021-05-31 10:14 UTC, slver-dragon commented on scripts/script.js
> +let triLine = document.getElementById("tri-line");
burgerMenu это в общем, а это как раз стиль для рисования трехлинника.

2021-05-31 10:16 UTC, slver-dragon commented on scripts/script.js
> +    : triLine.className = "tri-line";
Ну типа того, toggle это же как раз переключатель, два в одном.

2021-05-31 10:20 UTC, slver-dragon commented on scripts/script.js
> +  elementReplace(Number(targetElement.slice(5,targetElement.length)) - 1);
Денис, я исходил из твоей постановки задачи, если будет больше 10 элементов, то символа не хватит.

2021-06-01 07:03 UTC, DenisKalyanov requested changes

2021-06-01 07:03 UTC, DenisKalyanov commented on scripts/script.js
> +  console.log(newEl, current);
Удали console.log

2021-06-01 07:03 UTC, DenisKalyanov commented on scripts/script.js
> +  console.log(newEl, current);
delete

2021-06-01 07:08 UTC, merged